export const translateWindDir = (dir: string): string => {
    const map: Record<string, string> = {
        'N': 'เหนือ',
        'S': 'ใต้',
        'E': 'ตะวันออก',
        'W': 'ตะวันตก',
        'NE': 'ตะวันออกเฉียงเหนือ',
        'NW': 'ตะวันตกเฉียงเหนือ',
        'SE': 'ตะวันออกเฉียงใต้',
        'SW': 'ตะวันตกเฉียงใต้',
        'NNE': 'เหนือ-ตะวันออกเฉียงเหนือ',
        'ENE': 'ตะวันออก-ตะวันออกเฉียงเหนือ',
        'ESE': 'ตะวันออก-ตะวันออกเฉียงใต้',
        'SSE': 'ใต้-ตะวันออกเฉียงใต้',
        'SSW': 'ใต้-ตะวันตกเฉียงใต้',
        'WSW': 'ตะวันตก-ตะวันตกเฉียงใต้',
        'WNW': 'ตะวันตก-ตะวันตกเฉียงเหนือ',
        'NNW': 'เหนือ-ตะวันตกเฉียงเหนือ',
    };
    return map[dir] || dir;
};

export const translateCondition = (text: string): string => {
    const map: Record<string, string> = {
        'Partly cloudy': 'มีเมฆบางส่วน',
        'Partly Cloudy': 'มีเมฆบางส่วน',
        'Cloudy': 'เมฆมาก',
        'Overcast': 'เมฆครึ้ม',
        'Mist': 'หมอกลง',
        'Patchy rain possible': 'อาจมีฝนตกบางแห่ง',
        'Patchy snow possible': 'อาจมีหิมะตกบางแห่ง',
        'Patchy sleet possible': 'อาจมีฝนหิมะตกบางแห่ง',
        'Patchy freezing drizzle possible': 'อาจมีฝนละอองเยือกแข็งบางแห่ง',
        'Thundery outbreaks possible': 'อาจมีพายุฝนฟ้าคะนอง',
        'Blowing snow': 'หิมะพัดฟุ้ง',
        'Blizzard': 'พายุหิมะ',
        'Fog': 'หมอก',
        'Freezing fog': 'หมอกเยือกแข็ง',
        'Patchy light drizzle': 'ฝนละอองตกบางแห่ง',
        'Light drizzle': 'ฝนละออง',
        'Freezing drizzle': 'ฝนละอองเยือกแข็ง',
        'Heavy freezing drizzle': 'ฝนละอองเยือกแข็งตกหนัก',
        'Patchy light rain': 'ฝนตกเล็กน้อยเป็นหย่อมๆ',
        'Light rain': 'ฝนตกเล็กน้อย',
        'Moderate rain at times': 'ฝนตกปานกลางเป็นพักๆ',
        'Moderate rain': 'ฝนตกปานกลาง',
        'Heavy rain at times': 'ฝนตกหนักเป็นพักๆ',
        'Heavy rain': 'ฝนตกหนัก',
        'Light freezing rain': 'ฝนเยือกแข็งเล็กน้อย',
        'Moderate or heavy freezing rain': 'ฝนเยือกแข็งปานกลางถึงหนัก',
        'Light sleet': 'ฝนหิมะเล็กน้อย',
        'Moderate or heavy sleet': 'ฝนหิมะปานกลางถึงหนัก',
        'Patchy light snow': 'หิมะตกเล็กน้อยเป็นหย่อมๆ',
        'Light snow': 'หิมะเล็กน้อย',
        'Patchy moderate snow': 'หิมะตกปานกลางเป็นหย่อมๆ',
        'Moderate snow': 'หิมะปานกลาง',
        'Patchy heavy snow': 'หิมะตกหนักเป็นหย่อมๆ',
        'Heavy snow': 'หิมะตกหนัก',
        'Ice pellets': 'ลูกเห็บขนาดเล็ก',
        'Light rain shower': 'ฝนซู่เล็กน้อย',
        'Moderate or heavy rain shower': 'ฝนซู่ปานกลางถึงหนัก',
        'Torrential rain shower': 'ฝนตกลงมาอย่างหนัก',
        'Light sleet showers': 'ฝนหิมะซู่เล็กน้อย',
        'Moderate or heavy sleet showers': 'ฝนหิมะซู่ปานกลางถึงหนัก',
        'Light snow showers': 'หิมะซู่เล็กน้อย',
        'Moderate or heavy snow showers': 'หิมะซู่ปานกลางถึงหนัก',
        'Light showers of ice pellets': 'ลูกเห็บซู่เล็กน้อย',
        'Moderate or heavy showers of ice pellets': 'ลูกเห็บซู่ปานกลางถึงหนัก',
        'Patchy light rain with thunder': 'ฝนเล็กน้อยและพายุฝนฟ้าคะนองเป็นหย่อมๆ',
        'Moderate or heavy rain with thunder': 'ฝนปานกลางถึงหนักและพายุฝนฟ้าคะนอง',
        'Patchy light snow with thunder': 'หิมะเล็กน้อยและพายุฝนฟ้าคะนองเป็นหย่อมๆ',
        'Moderate or heavy snow with thunder': 'หิมะปานกลางถึงหนักและพายุฝนฟ้าคะนอง',
        'Clear': 'แจ่มใส',
        'Sunny': 'แดดจัด',
    };
    return map[text] || text;
};
